### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by DamienIrving**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by znicholls** [comment]
There should be a change to `{% set version = "1.0.0" %}` no?

**Comment by DamienIrving** [comment]
@znicholls I updated the version number to 1.0.0 and committed that change before realising I was supposed to fork and create a PR rather than commit directly to the repo. (i.e. the version update has already been done)

**Comment by znicholls** [comment]
got it

**Comment by znicholls** [comment]
Try the re-rendering command, that might help with the CI

**Comment by DamienIrving** [comment]
@conda-forge-admin, please rerender

**Comment by znicholls** [comment]
ipynbname isn't on conda (yet). I'm assuming this is now a hard dependency (?) and gitpython is no longer a dependency (?). There are a few ways to work around this: 

1. make ipynbname an optional dependency (pros: don't have to add it to conda forge, cons: have to tweak cmdline_provenance and really novice users might get confused)
2. add ipynbname to conda forge (pros: helpful for everyone, cons: have to spend 20 mins setting up)

**Comment by DamienIrving** [comment]
Ah, I was wondering what the problem could be!

Yep, `ipynbname` is a hard dependency (creating a command log entry for processes run in a notebook rather than via a command line script has come up as something people need) and `gitpython` is no longer a dependency (I've removed the git hash functionality).

I'd rather not make `ipynbname` optional (like you say, it makes things more confusing), so I'll have a go at adding it to conda-forge (will be a good exercise for me since I've never added one before). Is it customary to warn the authors of a package that you're going to add their package to conda-forge, or do people just go ahead and do it?

**Comment by znicholls** [comment]
> Is it customary to warn the authors of a package that you're going to add their package to conda-forge, or do people just go ahead and do it?

I'd raise an issue in their repo and give a day or two for a reply then just go for it. If you're in a massive rush, just go for it, you can always pull it down/give them control later.

**Comment by DamienIrving** [comment]
All fixed! @znicholls - I guess we just go ahead and merge?

**Comment by znicholls** [comment]
You got it! Nice work with ipynbname too

**Pull request merged**
